# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/cart.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/cart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/cart.proto\x12\x04\x63\x61rt\"$\n\x11\x43reateCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"!\n\x0eGetCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"G\n\x0e\x41\x64\x64ItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"8\n\x11RemoveItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\"#\n\x10\x43learCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"d\n\x08\x43\x61rtItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\r\n\x05total\x18\x05 \x01(\x02\"\xa2\x01\n\x0c\x43\x61rtResponse\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1d\n\x05items\x18\x03 \x03(\x0b\x32\x0e.cart.CartItem\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x02\x12\x13\n\x0btotal_items\x18\x05 \x01(\x05\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t2\xa6\x02\n\x0b\x43\x61rtService\x12\x39\n\nCreateCart\x12\x17.cart.CreateCartRequest\x1a\x12.cart.CartResponse\x12\x33\n\x07GetCart\x12\x14.cart.GetCartRequest\x1a\x12.cart.CartResponse\x12\x33\n\x07\x41\x64\x64Item\x12\x14.cart.AddItemRequest\x1a\x12.cart.CartResponse\x12\x39\n\nRemoveItem\x12\x17.cart.RemoveItemRequest\x1a\x12.cart.CartResponse\x12\x37\n\tClearCart\x12\x16.cart.ClearCartRequest\x1a\x12.cart.CartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECARTREQUEST']._serialized_start=26
  _globals['_CREATECARTREQUEST']._serialized_end=62
  _globals['_GETCARTREQUEST']._serialized_start=64
  _globals['_GETCARTREQUEST']._serialized_end=97
  _globals['_ADDITEMREQUEST']._serialized_start=99
  _globals['_ADDITEMREQUEST']._serialized_end=170
  _globals['_REMOVEITEMREQUEST']._serialized_start=172
  _globals['_REMOVEITEMREQUEST']._serialized_end=228
  _globals['_CLEARCARTREQUEST']._serialized_start=230
  _globals['_CLEARCARTREQUEST']._serialized_end=265
  _globals['_CARTITEM']._serialized_start=267
  _globals['_CARTITEM']._serialized_end=367
  _globals['_CARTRESPONSE']._serialized_start=370
  _globals['_CARTRESPONSE']._serialized_end=532
  _globals['_CARTSERVICE']._serialized_start=535
  _globals['_CARTSERVICE']._serialized_end=829
# @@protoc_insertion_point(module_scope)
