FROM python:3.9-slim

WORKDIR /app

# Устанавливаем системные зависимости для сборки (если нужны)
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Копируем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем прото-файлы и сгенерированный код
COPY *.proto .
COPY catalog_pb2.py .
COPY catalog_pb2_grpc.py .
COPY order_pb2.py  .
COPY order_pb2_grpc.py .
# Копируем основной код
COPY services/graphql_gateway.py .

EXPOSE 8081

# Запускаем сервер
CMD ["python", "graphql_gateway.py"]