FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY proto/auth.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. auth.proto

COPY services/auth_service.py .

CMD ["python", "auth_service.py"]