FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY proto/*.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. *.proto

COPY gateway/app.py .

CMD ["python", "app.py"]

