# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/notification.proto\x12\x0cnotification\"\xc8\x01\n\x13NotificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x41\n\x08metadata\x18\x05 \x03(\x0b\x32/.notification.NotificationRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"J\n\x18UserNotificationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"\x90\x01\n\x14NotificationResponse\x12\x17\n\x0fnotification_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x0c\n\x04sent\x18\x06 \x01(\x08\x12\x12\n\ncreated_at\x18\x07 \x01(\t\"e\n\x19UserNotificationsResponse\x12\x39\n\rnotifications\x18\x01 \x03(\x0b\x32\".notification.NotificationResponse\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xd9\x01\n\x13NotificationService\x12Y\n\x10SendNotification\x12!.notification.NotificationRequest\x1a\".notification.NotificationResponse\x12g\n\x14GetUserNotifications\x12&.notification.UserNotificationsRequest\x1a\'.notification.UserNotificationsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_NOTIFICATIONREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_NOTIFICATIONREQUEST']._serialized_start=43
  _globals['_NOTIFICATIONREQUEST']._serialized_end=243
  _globals['_NOTIFICATIONREQUEST_METADATAENTRY']._serialized_start=196
  _globals['_NOTIFICATIONREQUEST_METADATAENTRY']._serialized_end=243
  _globals['_USERNOTIFICATIONSREQUEST']._serialized_start=245
  _globals['_USERNOTIFICATIONSREQUEST']._serialized_end=319
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=322
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=466
  _globals['_USERNOTIFICATIONSRESPONSE']._serialized_start=468
  _globals['_USERNOTIFICATIONSRESPONSE']._serialized_end=569
  _globals['_NOTIFICATIONSERVICE']._serialized_start=572
  _globals['_NOTIFICATIONSERVICE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
