# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/payment.proto\x12\x07payment\"\x97\x01\n\x0ePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x16\n\x0epayment_method\x18\x04 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x05 \x01(\t\x12\x13\n\x0b\x63\x61rd_expiry\x18\x06 \x01(\t\x12\x10\n\x08\x63\x61rd_cvv\x18\x07 \x01(\t\"&\n\x10PaymentIdRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\"3\n\rRefundRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\xc0\x01\n\x0fPaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x16\n\x0etransaction_id\x18\x06 \x01(\t\x12\x16\n\x0epayment_method\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x12\x12\n\nupdated_at\x18\t \x01(\t2\xdb\x01\n\x0ePaymentService\x12\x43\n\x0eProcessPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\x12\x41\n\nGetPayment\x12\x19.payment.PaymentIdRequest\x1a\x18.payment.PaymentResponse\x12\x41\n\rRefundPayment\x12\x16.payment.RefundRequest\x1a\x18.payment.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTREQUEST']._serialized_start=33
  _globals['_PAYMENTREQUEST']._serialized_end=184
  _globals['_PAYMENTIDREQUEST']._serialized_start=186
  _globals['_PAYMENTIDREQUEST']._serialized_end=224
  _globals['_REFUNDREQUEST']._serialized_start=226
  _globals['_REFUNDREQUEST']._serialized_end=277
  _globals['_PAYMENTRESPONSE']._serialized_start=280
  _globals['_PAYMENTRESPONSE']._serialized_end=472
  _globals['_PAYMENTSERVICE']._serialized_start=475
  _globals['_PAYMENTSERVICE']._serialized_end=694
# @@protoc_insertion_point(module_scope)
